version: '3.8'
services:
  postgres:
    container_name: CompetitionPostgres
    image: postgres:14.4-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - COMPETITION_DB_USER=docker
      - COMPETITION_DB_PASSWORD=docker
      - COMPETITION_DB_NAME=competition
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d/
    ports:
      - '5434:5432'
