#!/bin/bash
set -e
export PGPASSWORD=$POSTGRES_PASSWORD;
psql -v ON_ERROR_STOP=1 -U "$POSTGRES_USER" <<-EOSQL
    CREATE USER $COMPETITION_DB_USER WITH PASSWORD '$COMPETITION_DB_PASSWORD';
    CREATE DATABASE $COMPETITION_DB_USER;
    GRANT ALL PRIVILEGES ON DATABASE $COMPETITION_DB_USER TO $COMPETITION_DB_USER;
    CREATE DATABASE $COMPETITION_DB_NAME;
    GRANT ALL PRIVILEGES ON DATABASE $COMPETITION_DB_NAME TO $COMPETITION_DB_USER;
EOSQL