spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/competition
    username: postgres
    password: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql
    hibernate:
      ddl-auto: update
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    user: postgres
    password: postgres
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
url:
  questionService: "http://localhost:8082/api/v1/questions/filter"

server:
  port: 8085