spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/competitionservice
    username: competition
    password: competition
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql
    hibernate:
      ddl-auto: none
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    user: competition
    password: competition
url:
  questionService: "http://localhost:8082/api/v1/questions"

server:
  port: 8085